version: '2.3'

services:

# Ciscoasa service
  ciscoasa:
    build: .
    container_name: ciscoasa
    restart: always
    stop_signal: SIGINT
    tmpfs:
     - /tmp/sensor:uid=65534,gid=65534
    network_mode: "host"
    ports:
     - "5000:5000/udp"
     - "8443:8443"
    image: "sissden/ciscoasa:latest"
    read_only: true
