version: '2.3'

services:

# glutton service
  glutton:
    build: .
    container_name: glutton
    restart: always
    tmpfs:
     - /tmp/sensor
     - /var/lib/glutton:uid=65534,gid=65534
    network_mode: "host"
    cap_add:
     - NET_ADMIN
    image: "sissden/glutton:latest"
    read_only: true
